name: Build spark 3.x

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build_spark3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark: [3.0.3, 3.1.3, 3.2.1, 3.3.0]
    env:
      hadoop: 3.3.3
      suffix: hadoop3
    steps:
      - name: clone spark repository
        uses: actions/checkout@v3
        with:
          repository: 'apache/spark'
          ref: 'v${{ matrix.spark }}'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: temurin
          check-latest: true
      - name: compile
        env:
          MAVEN_OPTS: -Xss64m -Xmx2g -XX:ReservedCodeCacheSize=1g -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
          MAVEN_CLI_OPTS: --no-transfer-progress
        run: |
          ./dev/make-distribution.sh --tgz --pip --name $suffix -Pyarn -Phive -Phive-thriftserver -Pkubernetes -Phadoop-cloud -Dhadoop.version=$hadoop -DskipTests -Dmaven.source.skip=true -Dmaven.site.skip=true -Dmaven.javadoc.skip=true
      - name: create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ matrix.spark }}"
          prerelease: false
          title: "Build of Spark version ${{ matrix.spark }}"
          files: |
            spark-${{ matrix.spark }}-bin-${{ env.suffix }}.tgz